@echo off
mkdir lib\core\constants
mkdir lib\core\theme
mkdir lib\core\utils
mkdir lib\core\widgets
mkdir lib\features\auth\bloc
mkdir lib\features\auth\data
mkdir lib\features\auth\models
mkdir lib\features\auth\presentation
mkdir lib\features\home\bloc
mkdir lib\features\home\data
mkdir lib\features\home\models
mkdir lib\features\home\presentation
mkdir lib\features\search\bloc
mkdir lib\features\search\data
mkdir lib\features\search\models
mkdir lib\features\search\presentation
mkdir lib\features\bookings\bloc
mkdir lib\features\bookings\data
mkdir lib\features\bookings\models
mkdir lib\features\bookings\presentation
mkdir lib\features\chat\bloc
mkdir lib\features\chat\data
mkdir lib\features\chat\models
mkdir lib\features\chat\presentation
mkdir lib\features\profile\bloc
mkdir lib\features\profile\data
mkdir lib\features\profile\models
mkdir lib\features\profile\presentation
mkdir lib\router
